- main.tf
- modules/admin/cluster.tf
- modules/admin/db.tf
- modules/admin/iam.tf
- modules/admin/loadbalancer.tf
- modules/admin/outputs.tf
- modules/admin/route53.tf
- modules/admin/security_groups.tf
- modules/admin/variables.tf
- modules/admin_vpc/main.tf
- modules/admin_vpc/outputs.tf
- modules/admin_vpc/variables.tf
- modules/cognito/main.tf
- modules/cognito/outputs.tf
- modules/cognito/variables.tf
- modules/radius/outputs.tf
- modules/vpc_flow_logs/variables.tf
- variables.tf
Terraform format has also been applied in this pull request.
> Set up infrastructure for admin portal

- buildspec.yml
- main.tf
- modules/radius/load_balancer.tf
- modules/radius/variables.tf
- variables.tf
Make transit gateway attachment dynamic, true on dev, pre-production and
production, false when applying locally.
> Public static IP addresses from BYOIP pool

- modules/admin_vpc/main.tf
> Run Admin in 3 AZs instead of 2

- buildspec.yml
- modules/radius/mysql.tf
This only applies to production, development and pre-production will
remain small databases.
1. Not publicly accessible
2. multi-az
3. deletion protection
4. logging
5. larger size (Improved IOPS)
> Prepare production database

- buildspec.yml
- main.tf
- modules/admin/outputs.tf
- modules/admin_read_replica/radius_read_replica.tf
- modules/admin_read_replica/security_groups_read_replica.tf
- modules/admin_read_replica/variables.tf
- variables.tf
This will contain the policies required by freeradius.
Will be replicated to the Radius VPC.
> Introduce admin read replica

- main.tf
This has changed to what is reported when debugging is turned off.
We can now create dashboard metrics in Grafana to match.
> Change outputs of log_filters

- buildspec.yml
- main.tf
- variables.tf
This does not accept separate credentials.
> Use admin credentials to connect to read replica

- modules/admin/db.tf
This is destructive and will destroy the existing databases.
> Recreate the admin databases in private subnets

- main.tf
- modules/admin/cluster.tf
- modules/admin/db.tf
- modules/admin/variables.tf
Refactor db variables into objects
> Update mysql engine version to 8.0 for admin db

- main.tf
- modules/radius/security_groups.tf
- modules/radius/variables.tf
This is required to reach MoJO DNS servers for OCSP name resolution.
> Allow EGRESS outbound traffic from the NAC servers VPC

- modules/admin/route53.tf
- modules/performance_testing/iam.tf
- modules/performance_testing/policies/config_bucket_policy.json
- modules/radius/route53.tf
Update a CNAME for radsec
Update the entire zone to network-access-control.service as well.
> Radsec route53

- modules/admin/route53.tf
- modules/radius/route53.tf
Reverts ministryofjustice/network-access-control-infrastructure#54
> Revert "Radsec route53"

- main.tf
Reverts ministryofjustice/network-access-control-infrastructure#53
> Revert "Recreate the VPC CIDR range"

- modules/radius/security_groups.tf
Modify rules to allow OCSP and remove unused udp egress rule.
Improve descriptions of rules.
> Refactor radius container security groups

- README.md
- documentation/deploying-nacs.md
This indicates how to trigger a manual deployment of each repository
> Update readme to include deployment guide

- modules/admin/cluster.tf
This is useful information for the pentesters
> Scan docker ECR image for Admin

- modules/radius/load_balancer.tf
Recommended path for load balancer.
> Enable radius logs for the load balancer

- modules/admin/db.tf
This is required to apply to the RDS database
> Add apply_method to db parameter groups

- modules/radius/load_balancer.tf
Add tags to elb resource to enable Prometheus monitoring.
> :bookmark: Add tags to elb resource

- main.tf
- modules/ecs_auto_scaling_radius/main.tf
- modules/ecs_auto_scaling_radius/variables.tf
- modules/radius/outputs.tf
This is required for metrics dimensions.
> Use the NLB ARN suffix instead of ARN

- scripts/eapol_test_mab.conf
- scripts/eapol_test_tls.conf
- scripts/run_perf_test.sh
- scripts/test_eap_mab.sh
- scripts/test_eap_tls.sh
This is removing some old sh scripts that did not need to be run anymore.
Combine with MAB as well.
> Change some of the performance test scripts

- buildspec.yml
- scripts/terraform_plan_or_apply.sh
Better to not use YAML for complex bash logic
> Move Terraform plan or apply to shell script

- main.tf
This will allow us to create detailed dashboards in Grafana and
distinguish between some radsec and eap transactions.
> Update metric filters for NACS server

- buildspec.yml
- documentation/debug-mode.md
- main.tf
- modules/radius/ecs_task_definition.tf
- modules/radius/variables.tf
- variables.tf
This is the default option and will be kept on.
> Remove ability to manage verbose logging

- modules/admin/ecs.tf
This will be used to do CSV imports asynchronously instead of on the
main thread which is slow.
> Create admin background workers service

- main.tf
- modules/admin/db.tf
- modules/admin/ecs.tf
- modules/admin/outputs.tf
- modules/admin/route53.tf
- modules/admin/variables.tf
- outputs.tf
This will allow showing the IPs on the admin portal
> Add server IP env variables to admin task

- main.tf
- fix the server IP addresses to contain from all availability zones
> Update Server IPs for Admin ECS Task Definition

- main.tf
Add log filter entry for server health check metric
> :stethoscope: Server Health Check Metric

- modules/performance_testing/user_data_radsec.sh
This conflicts with terraform template interpolation
> Replace radsecproxy version variable with static value

- modules/performance_testing/user_data_radsec.sh
This is required to pull files from s3
> Add awscli

- modules/performance_testing/user_data_radsec.sh
Added while loop to stagger container creation up to 500 per instance for testing.
> :zap: Create while loop to boost containers for testing

- modules/performance_testing/ec2_radsec.tf
- modules/performance_testing/user_data_radsec.sh
Changed instance count to zero to prevent resources running unnecessarily.
> :fire: Moved instance count to zero

- modules/performance_testing/ec2_radsec.tf
Commence testing with 10 EC2 instances.
> :wrench: Add 10 EC2 Instances

- modules/performance_testing/ec2_radsec.tf
> :wrench: Change EC2 instance to 20 hosts.

- modules/performance_testing/ec2_radsec.tf
> :wrench: Update EC2 instances to 0

- main.tf
- modules/admin/restore_db.tf
- modules/admin/variables.tf
This will create the backup which can be connected to in case of
disaster
> Ability to restore db by setting run_restore_from_backup

- modules/radius/ecr.tf
- modules/radius/ecr_nginx.tf
This change will be expanded upon, in future we will lock this down further so each account is environment specific.
> :lock: Update ECR IAM Policy

- .github/workflows/terraform-apply.yaml
- .github/workflows/terraform-static-analysis.yml
- .gitignore
- Makefile
- documentation/getting-started.md
- main.tf
- scripts/aws_ssm_get_parameters.sh
- scripts/generate-env-file.sh
- scripts/generate-github-env.sh
- versions.tf
This branch serves as an example of how the projects could be made more durable with consistency to 
- Terraform version definition.
- Makefile targets.
- TF_VARS and their retrieval from AWS SSM Parameterstore**
- Inclusion of example GitHub Action Workflow files
- Utility scripts to retrieve required TF_VARS from SSM parameter store and create environment specific ".env" file of use with the make file.
These additions do not make any material changes to the underlying code base, no updates or improvements beyond what has been stated above are included.
> 227 update makefile readme

- modules/admin/waf.tf
Updated WAF rules to count and log IP Addresses in prep for locking down nacs
> Updated WAF rules to count

- modules/admin/waf.tf
temp change, to capture all IPS hitting the service, rather than just the select IPS on the authorised IP list
> Capture all IPS

- Makefile
- data.tf
- main.tf
- modules/radius/load_balancer.tf
- modules/radius/variables.tf
- variables.tf
- Added security group for the production public NLB.
- Populated the security group with a list of allowed IPs (to be reviewed).
- Public access will remain open using the "nlb-public" security group until the list of allowed IPs is finalised.
> Public NLB security group

- modules/admin/db.tf
- modules/admin/restore_db.tf
- modules/admin_read_replica/radius_read_replica.tf
- Upgrading MySql version from 5.7 to 8.0 in NACS Admin and read replica
- Updated database name parameter to 'db name'  to address deprecation
- Temporarily Enabled Major version upgrade
> upgraded MySql version from 5.7 to  8.0

- main.tf
- modules/admin/db.tf
Reverting parameter changes that were enabled for DB upgrade
- Major upgrade
- apply Immediately
> RDS upgrade apply

- main.tf
- Changing apply_updates_immediately  values to true temporarily in preparation of production instance upgrade
> changing apply immediately 

- main.tf
Reverts ministryofjustice/network-access-control-infrastructure#284
> Revert "changing apply immediately "

- bootstrap/main.tf
- modules/admin/db.tf
- modules/bastion/bastion.tf
- versions.tf
Upgraded terraform AWS provider from 3 to 4
> AWS provider update

- modules/admin/auto_scaling.tf
Amended CW thresholds to stop scaling up and down simultaneously
> amended cw thresholds

- modules/vpc/endpoints.tf
Added STS endpoint for bastion use
> Added STS endpoint for bastion

- buildspec.yml
- main.tf
- modules/vpc/routes.tf
- modules/vpc/variables.tf
- scripts/aws_ssm_get_parameters.sh
- variables.tf
- Deployed Route for DHL OCS Endpoint
> added  route for DHL OCSP endpoint

- Makefile
- locals.tf
- secrets_manager.tf
> Seeding Secrete Manager secrets.

- .github/dependabot.yml
added dependabot for terraform and github actions
> added dependabot for terraform and github actions

- buildspec.yml
- Added variable back into buildpec.yml as it is used in script after terraform has run
> added hosted zone id back to buildspec

- main.tf
- modules/admin/waf.tf
Added  
```
lifecycle {
ignore_changes = [tags]
}
```
To get pipeline running without failures.
> ND-85 Hashicorp bug

- modules/admin/ecs.tf
- secrets_manager.tf
- service_admin.tf
Added cognito secrets to secrets manager
Removed them as env vars in the task definition
Changed source of secret to secret manager data block
> Added cognito secrets and removed from plain text in task definition

- outputs.tf
- versions.tf
> pin aws provider version

- modules/admin/ecs.tf
- added cognito secrets to background worker task definition
> moved cognito screts from background worker
