ministryofjustice/network-access-control-infrastructure

main.tf
modules/radius/load_balancer.tf
modules/radius/load_balancer_internal.tf
modules/vpc/main.tf
modules/vpc/variables.tf

This new range will allow us to integrate with the rest of the MoJ
network without overlapping CIDRs

Assign new CIDR range and run service in 3 AZs

---

buildspec.yml
main.tf
modules/radius/route53.tf
modules/radius/variables.tf
variables.tf

The domain we want to use is nac.justice.gov.uk
This will create a zone for each environment.
Local development will not execute this.

New hosted zone for NAC service

---

main.tf
modules/admin/cluster.tf
modules/admin/variables.tf
modules/radius/ecs_task_definition.tf
modules/radius/outputs.tf

The admin application will upload configuration files to this bucket.
Set this as an environment variable in ECS for the application to
access.

Set radius config bucket name in the admin task definition

---

main.tf
modules/admin/iam.tf
modules/admin/variables.tf
modules/radius/outputs.tf

The admin ECS tasks need access to the S3 configuration bucket to
publish the authorised macs.
Allow this by modifying the IAM policy associated with ECS.

Allow the admin application to publish configurations

---

modules/radius/outputs.tf

Currently we only deploy the public facing authentication service
when running through the pipeline.
Publish the internal service name to parameter store so it can be
accessed to deploy the internal service as well.

Export internal authentication service name

---

modules/radius/ecs_task_definition.tf

We currently enable CRL checking in production but we have no endpoint
to hit. Make this configurable and turn it off in production for now.
This sets the environment variable that FreeRadius can read to configure
the server at boot time.

Allow dynamically enabling or disabling CRL

---

modules/admin/cluster.tf

This will show metrics for things like CPU and memory which is useful
for troubleshooting.

Enable container insights for admin cluster

---

modules/admin/route53.tf

To improve the security posture of the Admin service we want to only
allow requests originating from the UK.
We've seen unauthorised access attempts from India, this will prevent
the DNS resolving, perventing such attacks.

Change admin Route53 routing policy to geo-location

---

main.tf
modules/ecs_auto_scaling/main.tf
modules/ecs_auto_scaling/variables.tf

This includes:
public facing RADIUS service
internal RADIUS service
Admin portal
This will scale out when the CPU > 70% for 1 minute
Scale in when the CPU is < 40% for 1 minute
The ECS desired task count will be changed to accomodate current load.

Add auto scaling for ECS services

---

modules/radius/load_balancer.tf
modules/radius/load_balancer_internal.tf

The load balancers are deployed to 3 AZs, containers run in 3 AZs.
Allow the load balancer to distribute the traffic across these AZs.
This improves robustness in the case of an AZ going down.

Enable cross zone load balancing

---

main.tf
modules/admin/cluster.tf
modules/admin/variables.tf

These values are required to deploy the internal radius cluster.
Currently only the internet facing cluster is being deployed.

Add internal service environment variables to admin task definition

---

buildspec.yml
main.tf
modules/radius/ecs_task_definition.tf
modules/radius/variables.tf
variables.tf

This allows full control of enabling OCSP, and overriding the endpoint
url.
This is required because not all environments have access to the production OCSP endpoint

Allow OCSP to be turned on or off and ability to override endpoint URL

---

modules/admin/loadbalancer.tf
modules/cognito/main.tf
modules/radius/load_balancer.tf

Changed the underscores to hyphens instead.

Even the longest name; radius-nac-lb-preproduction is only 27 chars.

---

modules/admin_vpc/main.tf
modules/admin_vpc/outputs.tf

We will move the admin database to private subnets for security.
Put in public subnets initially for debugging.

Create private subnets in the admin VPC

---

main.tf
modules/admin/cluster.tf
modules/admin/db.tf
modules/admin/loadbalancer.tf
modules/admin/security_groups.tf
modules/admin/variables.tf

This will be used to put the admin db in these subnets.
Refactor variables to be objects and grouped instead of individual.

Pass private subnet ids into the admin module

---

modules/admin/db.tf
modules/admin_read_replica/radius_read_replica.tf

RDS on version 8.0 does not support audit logs. This is required
information to send to OST platform.

Downgrade mysql engine version from 8.0 to 5.7

---

modules/admin/db.tf

We need to expose audit logs from the database for security logging.
Having changed the engine version back to 5.7 did not fix this, suspect
a bug on AWS side as this option is enabled.
Rename the databases to eliminate cached state and rebuild from scratch.

Rebuild RDS instances for admin db

---

modules/radius/load_balancer.tf

This should preserve the client IP address when the request
comes into FreeRadius.

Enable proxy protocol v2 on the NLB target groups

---

modules/radius/load_balancer.tf

This option was defaulting to false, should solve the issue of seeing
the NLB private IP address when requests come into FreeRadius.

Enable "preserve_client_ip" on target groups

---

modules/admin/route53.tf

Some DNS servers are not seen as coming from the UK, fall back to the
simple routing policy

Don't restrict DNS resolution to the UK

---

main.tf
modules/admin/outputs.tf
modules/admin_read_replica/radius_read_replica.tf
modules/admin_read_replica/variables.tf

The read replica is not replicating properly, this is due to the
replication source being an ARN value instead of an ID.

Use ID instead of ARN for replication source db

---

modules/vpc/transit_gateway_attachment.tf

To use the DNS servers required to resolve the OCSP endpoint, we need to
access them on the internal network.
A following commit will create the specific routes in the route tables
for the public subnets to redirect the traffic to the DNS service.

Create the transit gateway attachment in NAC public subnets

---

buildspec.yml
main.tf
modules/vpc/routes.tf
modules/vpc/variables.tf
variables.tf

To resolve DNS queries on the MoJO DNS service, we need to route these
requests to the private IP addresses.

Create routes from the public subnets to the transit gateway

---

modules/vpc/main.tf

This will use the MoJO DNS servers for the entire NAC VPC.

Use DHCP Options name servers to override the default DNS servers

---

main.tf

This was incorrect and clashes with the current IMA CIDR, causing issues
when attaching to the transit gateway / OCSP.

Update the VPC CIDR for NAC servers

---

Makefile
modules/performance_testing/main.tf
modules/performance_testing/user_data.sh
scripts/perf_test_setup.sh

The first slice of automating the setup for performance testing:
- Copy performance test and config file when booting EC2
- Add script for adding the IP addresses of performance test EC2s to the `clients.conf` file
- Add make command

Automate performance test config

---

buildspec.yml
main.tf
modules/radius/route53_resolver.tf
modules/radius/variables.tf
variables.tf

Resolver is outbound from our SG, and uses the 3 public/private subnets
Forward rule created, to with OCSP endpoint name from param store
Set target IPs of the forward rule to the mojo_dns_ips.

DNS Resolver and Rule

---

main.tf

Don't create the performance testing infrastructure until it's needed.

Disable performance testing

---

main.tf

This string does not have "Error: " in it so this metric is being
ignored. Update this so it shows up in Grafana.

Update "Ignored request" Cloudwatch metric

---

modules/vpc/routes.tf

If we're not attaching to the transit gateway when creating NACS in our
own workspace then there is no need to create routes pointing to it.

Don't create routes pointing to transit gateway for local development

---

main.tf
modules/admin/auto_scaling.tf
modules/ecs_auto_scaling_radius/main.tf
modules/ecs_auto_scaling_radius/variables.tf
modules/radius/outputs.tf

Instead of monitoring CPU and memory of the cluster, which doesn't
correlate directly with the amount of work that FreeRadius is doing,
look at the number of packets processed per container instead.
This gives us fine grained control over how much traffic/authentications we'd
like each container to process.
Currently set to 60 packets per container to test this scaling event, an
investigation needs to be done to find out what this number will be on
the production service. TBC during performance testing.

Update Radius cluster auto scaling

---

modules/admin/route53.tf

This was suspected to have caused issues with intermittent DNS
resolution of the admin portal. The cause was found to be missing
hosted zones in the parent AWS account.
We want to restrict admin URL resolution to the UK. Remains to be seen
if this reduces the number of unauthorised login attempts. We don't
expect administrators to be configuring NACS from outside the UK.

Re-instate geo-location routing policy for admin CNAME

---

modules/admin/waf.tf

AWS WAF will block all requests originating from non-GB locations.
This will prevent unauthorised access attempts.
This protects us from bots sending requests to IP addresses directly,
Route53 prevents attempts over DNS.

Add geolocation restrictions to admin ALB

---

modules/ecs_auto_scaling_radius/main.tf

The original numbers were set low for testing. Bump by x100 for
estimated production traffic to scale the cluster in or out.
This number is likely to fine-tuned based on performance testing
findings.

Bump autoscaling threshold x100

---

modules/admin/cluster.tf
modules/radius/ecs.tf

If a cluster (Radius or admin) has scaled due to load, we don't want to
reset that count by running terraform through the build pipelines.

Ignore desired count when applying

---

main.tf

As recommended here: https://github.com/ministryofjustice/staff#tags-for-application-and-services

Update AWS resource tags to conform to MoJ best practices

---

main.tf
modules/admin/auto_scaling.tf
modules/admin/cluster.tf
modules/admin/outputs.tf
modules/admin/variables.tf
modules/radius/outputs.tf

Cluster is a logical grouping of services and it doesn't make sense to
split the admin and radius service into separate clusters.

Move Admin service into the NACS ECS cluster

---

modules/admin/ecs.tf
modules/radius/ecs.tf

These don't have to be globally unique identifiers and are namespaced by
cluster. Use less verbose names.

Improve naming of NACS services in ECS cluster

---

buildspec.yml

This will output `terraform plan` before reaching the manual approval
stage. This change can then be accepted or rejected before being applied
to production infrastructure.

Allow planning production infrastructure changes

---

modules/admin/ecs.tf
modules/radius/ecs.tf

Latest version of Terraform does not require that resources be quoted as
strings.

Fix Terraform deprecation warnings

---

modules/admin/required_providers.tf
modules/admin_read_replica/required_providers.tf
modules/admin_vpc/required_providers.tf
modules/cognito/required_providers.tf
modules/ecs_auto_scaling_radius/required_providers.tf
modules/performance_testing/required_providers.tf
modules/radius/required_providers.tf
modules/vpc/required_providers.tf
modules/vpc_flow_logs/required_providers.tf

In the new versions of Terraform, required_providers have to be
explicity defined in the module using it.
Currently we get the following message whenever applying:
`Warning: Provider aws is undefined
on main.tf line 110, in module "radius":
110:     aws = aws.env
Module module.radius does **t declare a provider named aws.
If you wish to specify a provider configuration for the module, add an entry
for aws in the required_providers block within the module.
(and 10 more similar warnings elsewhere)`
Fix this by adding required_providers to each module.

Silence required provider warning message

---

main.tf

This is currently disabled within the module, better to disable at the
root level.

Disable performance testing in main.tf

---

main.tf
modules/radius/log_metrics.tf
modules/radius/variables.tf

This PR will allow us to scrape metrics from all environments without having to create a separate config file for each metric namespace.

:truck: consistent metric namespace across environments.

---

main.tf
modules/performance_testing/main.tf

This will force some metrics to be published to the Grafana dashboards

Re-enable performance testing module

---

main.tf

We will use the FreeRadius Access-Accept and Access-Reject metrics
instead of the freeradius logging module with "Login OK" and "Login
incorrect", these fire off more than once and will result in double
numbers of successful and unsuccessful authentications.

Change login incorrect metric

---

main.tf

You can have either:
write:fatal:unknown CA
read:fatal:unknown CA
We currently just monitor write:fatal:unknown CA.
Remove the prefix from the metric filter to match on both.

Make metric for "Unknown CA" more general

---

modules/admin/outputs.tf

This is required to deploy during a release in the build pipelines.

Output background worker service name

---

main.tf

This will make it easily searchable amongst the other NACS log groups.

Rename admin VPC flowlogs to be consistent

---

modules/admin_vpc/main.tf

Even though a name is supplied to the VPC resource, the Name tag takes
precedence. Currently both VPCs (radius and admin) have exactly the same
name, making it difficult to distinguish between.
Overwrite the name tag with the correct name sent to the module.

Overwrite the Name tag on the admin VPC

---

modules/radius/ecs.tf
modules/radius/ecs_task_definition.tf
modules/radius/iam.tf
modules/radius/load_balancer.tf
modules/radius/load_balancer_internal.tf
modules/radius/log_metrics.tf
modules/radius/logging.tf
modules/radius/outputs.tf
modules/radius/route53.tf
modules/radius/route53_radsec.tf
modules/radius/route53_resolver.tf
modules/radius/s3.tf
modules/radius/s3_certificates.tf
modules/radius/security_groups.tf
modules/radius/variables.tf

Performance testing will generate a large volume of logs, send this to a
temporary log group and point the metrics at this log group for
visibility in Grafana.

Send logs to temporary log group

---

modules/radius/ecs_task_definition.tf
modules/radius/log_metrics.tf
modules/radius/logging.tf

Performance testing has been concluded and the logs can be discarded.

Publish logs to original log group

---

modules/admin/auto_scaling.tf
modules/admin/ecs.tf
modules/admin/loadbalancer.tf
modules/admin/outputs.tf

The namespace indicates what type of resource it is, no need to repeat
in the name.

Remove redundant naming from resources

---

buildspec.yml
main.tf
modules/vpc/main.tf
modules/vpc/routes.tf
modules/vpc/variables.tf
variables.tf

This used to be locked down to a single IP, which doesn't make sense if
you're using DNS. Instead point all requests for that CIDR to the
Transit Gateway.

Update Transit Gateway routes to point to ATOS CIDR

---

main.tf

CloudWatch is case sensitive and "Error" in upper or lower case would be ignored. Add these explicitly, some could be raised by FreeRadius, Python, or Openssl, which all use different versions.

Add log filters for "error" and "ERROR"

---

.gitignore
main.tf
modules/radius/log_metrics.tf

This commit updates the `aws_cloudwatch_log_metric_filter` resource to account for the scenario where the `log_filters` list in `main.tf` contains entries with queries. The first resource handles 'normal' elements of the list and the latter resource is setup to filter for entries containing '?' and create metrics based off of this.

🔧 Update log metric filter logic

---

modules/radius/log_metrics.tf

This is required otherwise the logic of the statement is broken. ✏ Should have been included in #208

:wrench: Add length function

---

modules/admin/ecs.tf
modules/radius/ecr.tf
modules/radius/ecr_nginx.tf

This PR locks down the ECR IAM Policy to the AWS account id.

:lock: Update IAM AWS principal value

---

Makefile

make shell didn't work with aws commands, since the refactor to resolve the env variables issue. Needed to mount the local user's ".aws" config directory in the container's root directory.

Fix aws profile error

---

Makefile
README.md
bastion-rds-admin.tf
bastion-rds-servers.tf
documentation/rds-bastion.md
modules/admin/outputs.tf
modules/admin_vpc/outputs.tf
modules/vpc/outputs.tf
outputs.tf
scripts/aws_ssm_set_parameters.sh
scripts/get_db_parameters.sh

This code change adds the implementation of the RDS bastion as used in DHCP and DNS Infra project, for operation tasks in which direct access to the MySQL database is necessary.
Documentation for usage has been written and included.

575 provide a csv export of mab data from nacs implementation

---

scripts/publish_terraform_outputs.sh

During the publish terraform outputs operation the script could fail because the data has exceeded the standard tier of 4KB. Specifying "Intelligent-Tiering" for this parameter so that it will default to "Advanced" 8KB when necessary.

Update Parameter tier for terraform outputs

---

bastion-rds-admin.tf
bastion-rds-servers.tf

This was not required for the access to the endpoints.

Removed the vpc endpoint security from the rds bastion config

---

Makefile
data.tf
main.tf
modules/kinesis_firehose_xsiam/data.tf
modules/kinesis_firehose_xsiam/log_group_subscription.tf
modules/kinesis_firehose_xsiam/main.tf
modules/kinesis_firehose_xsiam/required_providers.tf
modules/kinesis_firehose_xsiam/s3.tf
modules/kinesis_firehose_xsiam/variable.tf

* added new xsiam firehose module
* Added ability to pull secrets in via data block
* Defined access_key & http_endpoint in secrets manager
- This is a draft waiting on endpoint details

Xsiam firehose

---

modules/admin/waf.tf

Updated the WAF rules to use AWS managed rules to protet the service from bad actors.
Added the following rules:
AWSManagedRulesCommonRuleSet
AWSManagedRulesAdminProtectionRuleSet
AWSManagedRulesKnownBadInputsRuleSet
AWSManagedRulesLinuxRuleSet
AWSManagedRulesUnixRuleSet
AWSManagedRulesAmazonIpReputationList
AWSManagedRulesBotControlRuleSet
Set the last priority rule to only allow gb
https://docs.aws.amazon.com/pdfs/waf/latest/developerguide/waf-dg.pdf#aws-managed-rule-groups-list

Updated WAF Rules

---

Makefile
modules/radius/load_balancer.tf
outputs.tf

- This PR will redeploy NLB to include security group 
- Security group rule will have the same rules as the task in NACs service
- Added Taint to make file(this is useful for when we need to force redeploy resources)

Nd 140 redeploy nac nlb with security group

---

buildspec.yml
main.tf
modules/vpc/main.tf
modules/vpc/outputs.tf
modules/vpc/routes.tf
modules/vpc/variables.tf
outputs.tf
scripts/aws_ssm_get_parameters.sh
variables.tf

- Deploys NAT Gateway with Elastic IP in Radius VPC
- Assigns NAT to the public route table with specific destination IP for OCSP DEP
- updates the gen-env script to accomodate new ssm parameter for ocsp_dep_ip
**Limitations acknowledged **
- **single** NAT could impact availability issue in the event of an AZ failure as the there are only one route table for public subnet.

 Added NAT gateway for the OCSP route to DEP

---

bootstrap/variables.tf

replacing current owner-email default entry for user who has left with lanwifi-devops@digital.justice.gov.uk ND-187

replacing current owner-email default entry for user who has left with lanwifi-devops@digital.justice.gov.uk

---

versions.tf

We can't update from 1.1.3 to a higher version without testing and reviewing the imact of these major version upgrades.
ND-214

Reverting Dependabot merge of Terraform version update.

---

Makefile
modules/performance_testing/s3.tf
modules/radius/load_balancer.tf
modules/radius/s3.tf
modules/radius/s3_certificates.tf

Updated s3 resources to get rid of deprecated warnings after upgrading AWS provider from 3 to 4.
Imported encryption resources, logging resources
acl and versioning not needed as they are standard on s3 buckets and don't need to be explicitly declared unless they need to be changed ie. acl from private to public, or versioning from enabled to disabled.

Updated s3 resources

---

modules/admin/ecs.tf
modules/radius/ecr.tf
modules/radius/ecr_nginx.tf

The current policy of
"Expire images older than 14 days"
Doesn't match our agreed policy as used in DNS & DHCP services. This also creates a risk that we can't rollback to previous known good images as any image older than 14 days will be expired.
This is actually hampering ability to diagnose a possible issue with a new Radius AMI.
The new policy has been agreed with the balance of retention and ability to rollback to known  good images that might be many months old. "Expire older versions of untagged images, keeping the latest 15"
ND-463

Align ECR retention policy with agreed policy

---

secrets_manager.tf

Descriptons for the the secrets should be added as a blank field is displayed otherwise.
ND-398

AWS Secrets Manager - descriptions

---

secrets_manager.tf

When other secrets have their descriptions added this will be necessary.
Also some secrets name/path have unhelpful legacy information in them which is misleading and the combination of a good description and AWS resources tag will help greatly in making the use clearer.
ND-398

Added service name to the secrets description

---

modules/bastion/bastion.tf
modules/bastion/user_data/user_data.sh

Initially this is to add the aws "s3-mojo-file-transfer-assume-role" to the instance. This allows access to the s3 file transfer bucket.
ND-510

Adding user_data script to RDS bastion

---

main.tf

Owner email in tags was outdated and the email wasn't in use. 
Changed to lanwifi-devops@digital.justice.gov.uk which is monitored.

amended owner email in tags

---

data.tf
locals.tf
modules/vpc/routes.tf
modules/vpc/variables.tf
vpc_radius.tf

NACs Public route table updated to reflect NHS Oxlease OCSP endpoint to be routed via NAT

Added vpc route for nhs oxlease
